### ISSUE TITLE
Kotsh example

### ISSUE THREAD

**Issue by InfamousBurns** [biom3tric/Kotsh#1]
Hey I’ve recently found your kotsh and was wondering if there would be a tutorial/example project that can go with this, I learn best from messing and tweaking examples just wondering as this looks pretty useful!

**Comment by biom3tric** [comment]
Thanks for the message :) If you have any question I can answer them. Actually, I profit of this issue to announce that Kotsh will maybe go deprecated in favor of LinkBuild, a similar library but made in .NET Core to offer possibility to work on Linux, MacOS and Windows. The project just started 2 days ago and I’m still thinking about the structure of the project, because it will now work using command line arguments and settings file to get it more modulable 👍 

Have a nice day
